pipeline {
    agent any

    tools {
        maven 'MAVEN-3.9'
        jdk 'JDK-17'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
        timeout(time: 45, unit: "MINUTES")
        disableConcurrentbuilds()
        timestamps()
    }

    parameters {
        string(name: BRANCH, defaultValue: 'main', description: "Git branch to build")
        choice(name: ENV, choices["dev", "stage", "prod"])
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Run test cases')
    }

    environment {
        AWS_REGION = "ap-south-1"
        CLUSTER_NAME = "EKS_PROD"
        IMAGE_NAME = "my-test-app"
        IMAGE_TAG = "${BUILD_NUMBER}-${params.ENV}"
        DOCKER_BUILDKIT = "1"
    }

    stages {
        stage('checkout') {
            steps {
                git branch: "${params.BRANCH}", url: 'github url', credentialsID: 'github-creds'
            }
        }

        stage('Build') {
            steps{
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            when { expression { params.RUN_TESTS } }

            parallel {

                stage('Unit Tests') {
                    steps {
                        sh 'mvn test'
                    }
                    post {
                        junit '**/target/surefire-report/*.xml'
                    }
                }

                stage('Code Quality') {
                    steps {
                        sh '''
                        mvn sonar:sonar \
                        -Dsonar.projectkey=java-app \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.login=$SONAR_TOKEN
                        '''
                    }
                }

                stage('Security Scan (Dependencies)') {
                    steps {
                        sh 'mvn org.owasp:dependency-check-maven:check || true'
                    }
                }
            }
        }

        stage('Docker Build & Scan') {
            steps {
                sh '''
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                # Trivy scan
                docker run --rm aquasec/trivy image ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Publish') {
            steps {
                script {
                    def ACCOUNT_ID = sh(
                        script: "aws sts get-caller-identity --query Account --output text",
                        returnStdout: true
                    ).trim()

                    env.ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}"
                }
            }
        }
    }

}